### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by woody-ltd** [aageorg/Testing-tasks#1]
https://github.com/aageorg/Testing-tasks/blob/1e3e938fc0241880456b62a1ee07e6257da4c391/keenetic/main.go#L72
- Follow convenstion for constuctors in Go - they are not a part of an interface -https://stackoverflow.com/questions/18125625/constructors-in-go

- ListenAndServe processes each request received in separate go routine. Taking this into account, do we still need some other go routines for background processing? Get rid of go routines started in lines 232, 238, 260, 286

https://github.com/aageorg/Testing-tasks/blob/1e3e938fc0241880456b62a1ee07e6257da4c391/keenetic/main.go#L244
- Handlers are traditionally defined as a named functions and not inside main() line 244

- Why do we need so many code lines for timeout handling? Lines 288, 105-118, 127-135. Think how to use Context with timeout directly in GET handler.

**Comment by aageorg** [comment]
Thank you for the feedback and the detailed review. I have tried to take all the comments into account.

**Comment by aageorg** [comment]
Thank you for the detailed code review and the feedback. I have tried to take all the comments into account.
